from fastapi import FastAPI, Response
from pydantic import BaseModel
from typing import Optional
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from io import BytesIO
import os, time

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(
        "app.main:app",
        host="0.0.0.0",
        port=8080,
        reload=True,  # handy for local dev
    )

app = FastAPI(title="Sample VPN Backend", version="1.0.0")


class EchoIn(BaseModel):
    message: str
    size_kb: Optional[int] = 0 # extra payload for testing


@app.get("/health")
def health():
    return {"status": "ok", "service": "sample-vpn-backend", "ts": int(time.time())}


@app.post("/api/echo")
def echo(body: EchoIn):
    filler = "x" * (body.size_kb * 1024)
    return {"echo": body.message, "size_kb": body.size_kb, "filler": filler}


@app.get("/docs/meta")
def meta():
    return {
            "service": "sample-vpn-backend",
            "env": {
                "ENV": os.getenv("ENV", "dev"),
                "REGION": os.getenv("REGION", "eu-west-1"),
                },
            }


@app.get("/report.pdf")
def report_pdf():
    # Generate a simple PDF in-memory
    buf = BytesIO()
    p = canvas.Canvas(buf, pagesize=A4)
    w, h = A4
    p.setFont("Helvetica", 20)
    p.drawString(72, h-72, "Sample VPN PDF Report")
    p.setFont("Helvetica", 12)
    p.drawString(72, h-120, "This PDF was generated by FastAPI + reportlab.")
    p.drawString(72, h-140, "Great for testing binary responses over VPN.")
    p.showPage()
    p.save()
    pdf = buf.getvalue()
    headers = {
            "Content-Type": "application/pdf",
            "Content-Disposition": "inline; filename=report.pdf",
            "Cache-Control": "no-store",
            }
    return Response(content=pdf, media_type="application/pdf", headers=headers)
